<?php

declare(strict_types=1);

namespace miralsoft\weclapp\api\DTO;

use DateTimeImmutable;

/**
 * Represents a single status history entry on a sales order, sales invoice or quotation.
 *
 * Maps to the status history sub-schema used across multiple weclapp document types.
 * All fields are readOnly — this is a historical log entry generated by weclapp.
 *
 * The `creditLimitExceeded` field is only populated on sales order status history
 * entries; it will be false for invoices and quotations.
 */
final class StatusHistoryDTO extends AbstractDTO
{
    /**
     * @param string|null $status               The document status at this point in time (readOnly).
     * @param int|null    $statusDate           Date the status change occurred in epoch milliseconds (readOnly).
     * @param string|null $userId               ID of the user who triggered the status change (readOnly).
     * @param bool        $creditLimitExceeded  True if the customer credit limit was exceeded at this status (readOnly, salesOrder only).
     */
    public function __construct(
        public readonly ?string $status,
        public readonly ?int    $statusDate,
        public readonly ?string $userId,
        public readonly bool    $creditLimitExceeded,
    ) {}

    /**
     * Create a StatusHistoryDTO from a raw weclapp API response array.
     *
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            status:              self::strOrNull($data, 'status'),
            statusDate:          self::intOrNull($data, 'statusDate'),
            userId:              self::strOrNull($data, 'userId'),
            creditLimitExceeded: self::bool($data, 'creditLimitExceeded'),
        );
    }

    /**
     * Returns the status change date as a DateTimeImmutable object, or null if not set.
     */
    public function getStatusDate(): ?DateTimeImmutable
    {
        return self::dateFromEpochMs(['statusDate' => $this->statusDate], 'statusDate');
    }
}
